### ISSUE TITLE
Move compiled binary to correct location after compilation

### ISSUE THREAD

**Issue by LeoAtGit** [Grumbel/jstest-gtk#15]
If I follow the steps in your README regarding the compilation of your program, I can't start it, because 
`"Error: Failed to open file '/<omitted>/jstest-gtk/build/data/xbox360_small.png': No such file or directory"`
I have to move the binary to the top level (out of the build directory) to start it.
Maybe you could add that to your README, or you could change the directory cmake stores the binary in.

If you need more information, just ask.

**Comment by angerangel** [comment]
I confirm the issue, another solution is or copy the the **data** folder in build directory.
