### ISSUE TITLE
Window runs off-screen on small devices

### ISSUE THREAD

**Issue by AGausmann** [Grumbel/jstest-gtk#5]
I installed this on my netbook so I could mess with custom HID devices for my robotics team. However, it is hard to use because the button indicators and some buttons are off-screen.
Could you alter the GUI to make it fit small-resolution screens (1024x600)?
![JSTest Screenshot](http://i.imgur.com/eEzUJYd.jpg)

**Comment by Grumbel** [comment]
I removed the non-working profile management and added a `--simple` option that hides the graphical representation of sticks, that should give a bit more vertical space.
