### ISSUE TITLE
Feature request: rumble support

### ISSUE THREAD

**Issue by lozbrown** [Grumbel/jstest-gtk#7]
Could this be expanded to include a test for rumble ?

**Comment by Grumbel** [comment]
Not without some larger changes, as rumble is part of the Linux evdev interface, not the old jsdev interface that jstest-gtk is currently using.

The console tool `fftest` can be used to test force feedback devices in Linux in the meantime.

**Comment by lozbrown** [comment]
Strangely fftest doesn't seem to work, I have a ps3 sixaxis controller and a similar fake one... These actually rumble in BioShock infinite. However they do nothing with fftest.

I'm largely of the opinion that the usage of the terminal shouldn't be necessary. It's daunting for novices and has a high entry understanding requirement.

**Comment by Grumbel** [comment]
I started another tool: [evtest-qt](https://github.com/Grumbel/evtest-qt). It doesn't yet have rumble support either, but it will be much more straight forward to add there. jstest-gtk is kind of obsolete at this point, as no modern game uses the jsdev interface any more. So there probably won't be any further development outside of keeping it running.
