### ISSUE TITLE
Add explicit "-std=c++11" option

### ISSUE THREAD

**Issue by klokik** [Grumbel/jstest-gtk#9]
Some compilers are configured to use c++03 standart by default and fail to build the code if you don't say them to use a newer version.

**Comment by Grumbel** [comment]
What error message are you getting? The code should be C++03, not C++11 as it was mostly written back in 2009, if I remember correctly.

**Comment by klokik** [comment]
It seems to complain on sigc++ headers, as stated on their site "libsigc++ version 2.5.1 and later require a compiler with C++11 support".
